### ISSUE TITLE
Support for Liquibase migration 

### ISSUE THREAD

**Issue by swanandvk** [medly/norm#186]
shall we a provide a flag in configuration to automatically execute migration before running norm 
it will help to keep the db schema updated for generating sql instead of running it manually if there are schema/sql changes in the project repository

**Comment by kdabir** [comment]
This would implicitly assume everyone is using liquibase which may not be the case. From end user perspective all they need to do is add `normCodegen dependsOn theirMigrationTask` in `build.gradle` to run migration every time before codegen is executed. WDYT?

**Comment by swanandvk** [comment]
> This would implicitly assume everyone is using liquibase which may not be the case. From end user perspective all they need to do is add `normCodegen dependsOn theirMigrationTask` in `build.gradle` to run migration every time before codegen is executed. WDYT?

Makes sense 👍 
closing this one . Thanks
